aliases:
    fleeks: cd ~/.local/share/fleek
    lg: lazygit
    mpv: flatpak run --command=mpv io.mpv.Mpv
    tmux: zellij
    yt-dlp: flatpak run --command=yt-dlp org.nickvision.tubeconverter
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - exa
    - bat
    - lazygit
    - devbox
    - gh
    - syncthing
    - zellij
    - mprocs
    - stow
    - du-dust
    - gallery-dl
    - rclone
    - act
    - cosign
    - neovim
    - go
    - binutils_nogold
    - asciinema
    - lf
    - dive
paths:
    - $HOME/go/bin
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: posi
      os: linux
      username: tulili
    - arch: x86_64
      hostname: tower
      os: linux
      username: tulili
track: ""
unfree: true
users:
    - email: tulilirockz.pub+git@gmail.com
      name: tulili
      ssh_private_key_file: ~/.ssh/git
      ssh_public_key_file: ~/.ssh/git.pub
      username: tulili
