aliases:
    du: dust
    yt-dlp: flatpak run --command=yt-dlp org.nickvision.tubeconverter
    mpv: flatpak run --command=mpv io.mpv.Mpv
    fleeks: cd ~/.local/share/fleek
bling: low
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: true
    autopush: false
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - exa
    - bat
    - lazygit
    - devbox
    - gh
    - syncthing
    - zellij
    - mprocs
    - stow
    - du-dust
    - gallery-dl
    - shellcheck
    - rclone
    - act
    - cosign
    - neovim
paths:
    - $HOME/go/bin
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: posi
      os: linux
      username: tulili
unfree: true
users:
    - email: tulilirockz.pub+git@gmail.com
      name: Tulili
      ssh_private_key_file: ~/.ssh/git
      ssh_public_key_file: ~/.ssh/git.pub
      username: tulili
