aliases:
    du: dust
    fleeks: cd ~/.local/share/fleek
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - yadm
    - exa
    - bat
    - devbox
    - gh
    - lm_sensors
    - syncthing
    - zellij
    - mprocs
    - stow
    - du-dust
    - gallery-dl
    - shellcheck
    - rclone
    - act
    - cosign
    - flutter-unwrapped
    - flutterPackages.stable
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: posi
      os: linux
      username: tulili
unfree: true
users:
    - email: tulilirockz.pub+git@gmail.com
      name: Tulili
      ssh_private_key_file: ~/.ssh/git
      ssh_public_key_file: ~/.ssh/git.pub
      username: tulili
